import { Link } from "react-router-dom";
import { ShieldCheck, Sparkles, Workflow, Database, Eye, Network, ArrowRight, Brain, FileSearch, MessageSquareText, AlertOctagon } from "lucide-react";

const FEATURES = [
  { icon: Brain, title: "10-Agent LangGraph Pipeline", desc: "Complaints flow through 10 specialist AI agents — understanding, intent, NER, sentiment, severity, duplicate, RAG, recommendation, explainability, response." },
  { icon: FileSearch, title: "RAG Knowledge Retrieval", desc: "Semantic search over refund, return, warranty, shipping, fraud and SOP documents — domain-aware, cited in every recommendation." },
  { icon: Eye, title: "Explainable AI", desc: "Every decision ships with evidence, policy basis, similar past complaints and a confidence score. No black boxes." },
  { icon: AlertOctagon, title: "Duplicate Detection", desc: "TF-IDF cosine similarity over historical complaints surfaces duplicates before a new ticket is created." },
  { icon: MessageSquareText, title: "Auto-Generated Responses", desc: "Customer-facing email, support notes and manager notes generated by Claude Sonnet 4.5 — professionally toned." },
  { icon: Network, title: "Multi-Domain Ready", desc: "E-commerce, Banking, Telecom, Insurance, Healthcare, Government, Utilities — pick a domain and the right policies load automatically." },
];

const STACK = ["FastAPI", "LangGraph", "Claude Sonnet 4.5", "MongoDB", "React", "Tailwind", "scikit-learn (TF-IDF)", "Recharts"];

export default function Landing() {
  return (
    <div className="min-h-screen bg-[#F8FAFC]" data-testid="landing-page">
      <header className="max-w-7xl mx-auto px-6 py-5 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-blue-600 to-blue-500 flex items-center justify-center">
            <ShieldCheck className="w-5 h-5 text-white" />
          </div>
          <span className="font-heading font-semibold text-lg text-slate-900">ComplaintIQ</span>
        </div>
        <div className="flex items-center gap-3">
          <Link to="/login" data-testid="header-login" className="text-sm font-medium text-slate-600 hover:text-slate-900 px-4 py-2">Log in</Link>
          <Link to="/register" data-testid="header-register" className="btn-primary">Get Started <ArrowRight className="w-4 h-4" /></Link>
        </div>
      </header>

      <section className="max-w-7xl mx-auto px-6 pt-12 pb-20 grid lg:grid-cols-2 gap-12 items-center">
        <div>
          <div className="inline-flex items-center gap-2 bg-blue-50 text-blue-700 text-xs font-medium px-3 py-1.5 rounded-full mb-6">
            <Sparkles className="w-3.5 h-3.5" /> Agentic AI · LangGraph · RAG · Explainable AI
          </div>
          <h1 className="font-heading text-4xl sm:text-5xl lg:text-6xl font-semibold tracking-tight text-slate-900 leading-[1.05]">
            Turn every consumer complaint into a <span className="text-blue-600">resolved one</span>.
          </h1>
          <p className="mt-6 text-base text-slate-600 leading-relaxed max-w-xl">
            ComplaintIQ is a multi-agent platform that understands, classifies, prioritizes and resolves customer complaints in seconds — with full transparency on every AI decision.
          </p>
          <div className="mt-8 flex flex-wrap gap-3">
            <Link to="/register" data-testid="hero-cta-register" className="btn-primary">Try the demo <ArrowRight className="w-4 h-4" /></Link>
            <Link to="/login" data-testid="hero-cta-login" className="btn-secondary">Log in with demo accounts</Link>
          </div>
          <div className="mt-8 grid grid-cols-3 gap-4 max-w-md">
            <Stat n="10" l="AI Agents" />
            <Stat n="7" l="Industries" />
            <Stat n="<10s" l="Decision Time" />
          </div>
        </div>
        <div className="card-soft p-6">
          <div className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400 mb-4">Live agent pipeline</div>
          <ol className="space-y-3">
            {["Complaint Understanding", "Intent Classification", "Entity Recognition", "Sentiment & Emotion", "Severity Prediction", "Duplicate Detection", "Knowledge Retrieval (RAG)", "Resolution Recommendation", "Explainability", "Response Generation"].map((s, i) => (
              <li key={s} className="flex items-center gap-3">
                <div className="w-7 h-7 rounded-full bg-blue-50 text-blue-700 text-xs font-semibold flex items-center justify-center">{i+1}</div>
                <span className="text-sm text-slate-700">{s}</span>
                <Workflow className="w-3.5 h-3.5 text-slate-300 ml-auto" />
              </li>
            ))}
          </ol>
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-6 py-16">
        <h2 className="font-heading text-2xl sm:text-3xl font-semibold text-slate-900">Built for decision intelligence, not chat.</h2>
        <p className="mt-3 text-slate-600 max-w-2xl">Backend-heavy by design. Every output is structured, auditable and explainable.</p>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5 mt-10">
          {FEATURES.map(({ icon: Icon, title, desc }) => (
            <div key={title} className="card-soft p-6">
              <div className="w-10 h-10 rounded-[10px] bg-blue-50 text-blue-600 flex items-center justify-center mb-4"><Icon className="w-5 h-5" /></div>
              <h3 className="font-heading text-lg font-medium text-slate-900">{title}</h3>
              <p className="mt-2 text-sm text-slate-600 leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="max-w-7xl mx-auto px-6 py-12">
        <div className="card-soft p-8">
          <div className="text-xs font-semibold uppercase tracking-[0.2em] text-slate-400 mb-3">Technology stack</div>
          <div className="flex flex-wrap gap-2">
            {STACK.map((s) => (<span key={s} className="badge-pill bg-slate-100 text-slate-700">{s}</span>))}
          </div>
        </div>
      </section>

      <footer className="max-w-7xl mx-auto px-6 py-12 text-center text-sm text-slate-500">
        ComplaintIQ · An M.Tech research-grade Agentic AI platform.
      </footer>
    </div>
  );
}

function Stat({ n, l }) {
  return (
    <div>
      <div className="font-heading text-2xl font-semibold text-slate-900">{n}</div>
      <div className="text-xs text-slate-500 mt-0.5">{l}</div>
    </div>
  );
}
